type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
  phoneNumber: String
  address: String
}

type Restaurant @table {
  name: String!
  address: String!
  phone: String!
  createdAt: Timestamp!
  description: String
  cuisineType: String
  logoUrl: String
  openingHours: String
}

type Category @table {
  name: String!
  restaurant: Restaurant!
  description: String
  displayOrder: Int
}

type MenuItem @table {
  name: String!
  price: Float!
  restaurant: Restaurant!
  category: Category!
  createdAt: Timestamp!
  description: String
  imageUrl: String
  quantityAvailable: Int
}

type Order @table {
  user: User!
  restaurant: Restaurant!
  orderDate: Timestamp!
  totalAmount: Float!
  status: String!
  deliveryAddress: String
  notes: String
}

type OrderItem @table(key: ["order", "menuItem"]) {
  order: Order!
  menuItem: MenuItem!
  quantity: Int!
  priceAtTimeOfOrder: Float!
}